---
title: "flat_get_one_file_size.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_one_file_size

```{r development-get_one_file_size}
# Prepare the code of your function here

file.size("DESCRIPTION")

data.frame(
  nom_fichier = "DESCRIPTION",
  taille = file.size("DESCRIPTION")
)
```

```{r function-get_one_file_size}
#' get_one_file_size Title
#'
#' @return df un dataframe avec les infos sur le fichier
#' @param path_fichier le chemin vers le fichier
#' @export
#'
#' @examples
get_one_file_size <- function(path_fichier) {
  
  if(!file.exists(path_fichier)){
    stop("Votre fichier n'existe pas !!!")
  }
  
  df <- data.frame(
    nom_fichier = basename(path_fichier),
    taille = file.size(path_fichier)
  )
  return(df)
}
```

```{r examples-get_one_file_size}
get_one_file_size(glue::glue("{system.file(package = 'toolboxMael')}/nyc_squirrels_sample.csv"))
```

```{r tests-get_one_file_size}
test_that("get_one_file_size works", {
  expect_true(inherits(get_one_file_size, "function"))
  
  expect_error(object = get_one_file_size(glue::glue("{system.file(package = 'toolboxMael')}/nyc_squirrels.csv")),
               regexp = "Votre fichier n'existe pas !!!")
  expect_equal(object = get_one_file_size(glue::glue("{system.file(package = 'toolboxMael')}/nyc_squirrels_sample.csv")),
               expected = data.frame(
                 nom_fichier = "nyc_squirrels_sample.csv",
                 taille = 54650
               ))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_get_one_file_size.Rmd", vignette_name = "Get file size")
```

