# WARNING - Generated by {fusen} from dev/flat_get_one_file_size.Rmd: do not edit by hand # nolint: line_length_linter.

#' get_one_file_size Title
#'
#' @return df un dataframe avec les infos sur le fichier
#' @param path_fichier le chemin vers le fichier
#' @export
#'
#' @examples
#' get_one_file_size(glue::glue("{system.file(package = 'toolboxMael')}/nyc_squirrels_sample.csv"))
get_one_file_size <- function(path_fichier) {
  
  if(!file.exists(path_fichier)){
    stop("Votre fichier n'existe pas !!!")
  }
  
  df <- data.frame(
    nom_fichier = basename(path_fichier),
    taille = file.size(path_fichier)
  )
  return(df)
}
